apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: activity-log-dapr
spec:
  type: pubsub.azure.eventhubs
  version: v1
  metadata:
  - name: connectionString
    value: "Endpoint=sb://localhost:5672/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=test;UseDevelopmentEmulator=true;"
  - name: eventHubName
    value: "activity-log"